import type { Metadata } from 'next'
import { requireSession } from '@/lib/auth/session'
import { createSupabaseServerClient } from '@/lib/supabase/server'
import { siteUrl } from '@/lib/env'
import {
  Alert,
  Badge,
  Card,
  CardBody,
  CardHeader,
  CardTitle,
  EmptyState,
  PageHeader,
  Stat,
  Table,
  TableWrap,
  Td,
  Th,
} from '@/components/ui'
import { CopyButton } from '@/components/deposit-forms'
import { formatDate, formatUsdt } from '@/lib/format'
import type { PlatformSetting, TeamMember, TeamSummary } from '@/types/database'

export const metadata: Metadata = { title: 'Team' }
export const dynamic = 'force-dynamic'

export default async function TeamPage() {
  const session = await requireSession('/team')
  const supabase = await createSupabaseServerClient()

  const [{ data: summaryRaw }, { data: membersRaw }, { data: settings }] = await Promise.all([
    supabase.rpc('get_team_summary', { p_user_id: session.userId }),
    supabase.rpc('get_team_members', { p_user_id: session.userId, p_level: null }),
    supabase
      .from('platform_settings')
      .select('key, value')
      .in('key', [
        'referral_level1_percent',
        'referral_level2_percent',
        'referral_level3_percent',
        'referral_rewards_enabled',
      ])
      .returns<PlatformSetting[]>(),
  ])

  const summary = (summaryRaw as TeamSummary) ?? null
  const members = (membersRaw as TeamMember[]) ?? []
  const settingMap = new Map((settings ?? []).map((s) => [s.key, s.value]))

  const percent = (level: number) => {
    const raw = settingMap.get(`referral_level${level}_percent`)
    const n = Number(raw ?? 0)
    return Number.isFinite(n) ? n * 100 : 0
  }
  const rewardsEnabled = String(settingMap.get('referral_rewards_enabled') ?? 'true') === 'true'

  const inviteLink = `${siteUrl()}/register?ref=${session.profile.referral_code}`
  const byLevel = (level: number) => members.filter((m) => m.level === level)

  return (
    <div className="space-y-6">
      <PageHeader
        title="My team"
        description="Registration is invitation-only. Anyone who signs up with your link joins your team."
      />

      <Card>
        <CardHeader>
          <CardTitle>Your invitation</CardTitle>
        </CardHeader>
        <CardBody className="space-y-4 pt-0">
          <div>
            <p className="text-xs uppercase tracking-wide text-ink-subtle">Invitation code</p>
            <div className="mt-1 flex items-center gap-2">
              <code className="rounded-lg bg-surface-2 px-3 py-2 font-mono text-lg font-semibold tracking-widest">
                {session.profile.referral_code}
              </code>
              <CopyButton value={session.profile.referral_code} label="Copy code" />
            </div>
          </div>

          <div>
            <p className="text-xs uppercase tracking-wide text-ink-subtle">Invitation link</p>
            <div className="mt-1 flex items-start gap-2">
              <code className="min-w-0 flex-1 break-all rounded-lg bg-surface-2 px-2.5 py-2 font-mono text-xs">
                {inviteLink}
              </code>
              <CopyButton value={inviteLink} label="Copy link" />
            </div>
          </div>
        </CardBody>
      </Card>

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <Stat label="Total team" value={summary?.total ?? 0} sub="Across all three levels" />
        <Stat label="Level 1 (direct)" value={summary?.level1 ?? 0} sub={`${percent(1).toFixed(1)}% commission`} />
        <Stat label="Level 2" value={summary?.level2 ?? 0} sub={`${percent(2).toFixed(1)}% commission`} />
        <Stat label="Level 3" value={summary?.level3 ?? 0} sub={`${percent(3).toFixed(1)}% commission`} />
      </div>

      <div className="grid gap-3 sm:grid-cols-2">
        <Stat
          label="Commission earned"
          value={formatUsdt(summary?.total_commission ?? 0)}
          tone="positive"
          sub="Paid into your internal platform balance"
        />
        <Stat
          label="Members with an active plan"
          value={summary?.active_members ?? 0}
          sub={`of ${summary?.total ?? 0} total`}
        />
      </div>

      <Alert tone="info" title="How referral commission is funded">
        Commission is a share of revenue the platform actually collects: when a team member activates a VIP plan, a
        configured percentage of that activation fee is credited to their upline. Nothing is paid out of another
        member&apos;s deposit, and no commission is generated by deposits alone.
        {!rewardsEnabled ? ' Referral commissions are currently disabled by the operator.' : ''}
      </Alert>

      {members.length === 0 ? (
        <Card>
          <CardBody>
            <EmptyState
              title="No team members yet"
              description="Share your invitation link. Anyone who registers with it appears here, along with everyone they invite, up to three levels deep."
            />
          </CardBody>
        </Card>
      ) : (
        [1, 2, 3].map((level) => {
          const rows = byLevel(level)
          if (rows.length === 0) return null

          return (
            <Card key={level}>
              <CardHeader>
                <CardTitle>Level {level}</CardTitle>
                <Badge tone="brand">
                  {rows.length} member{rows.length === 1 ? '' : 's'} · {percent(level).toFixed(1)}%
                </Badge>
              </CardHeader>
              <CardBody className="pt-0">
                <TableWrap>
                  <Table>
                    <thead>
                      <tr>
                        <Th>Member</Th>
                        <Th>Joined</Th>
                        <Th>Plan</Th>
                        <Th>Status</Th>
                      </tr>
                    </thead>
                    <tbody>
                      {rows.map((m) => (
                        <tr key={m.user_id}>
                          <Td>
                            <p className="font-medium">{m.username ?? 'Member'}</p>
                            <p className="text-xs text-ink-subtle">{m.masked_email}</p>
                          </Td>
                          <Td className="whitespace-nowrap text-ink-muted">{formatDate(m.joined_at)}</Td>
                          <Td>{m.vip_plan ? <Badge tone="brand">{m.vip_plan}</Badge> : <span className="text-ink-subtle">—</span>}</Td>
                          <Td>
                            <Badge tone={m.is_active ? 'positive' : 'neutral'}>{m.is_active ? 'Active' : 'Inactive'}</Badge>
                          </Td>
                        </tr>
                      ))}
                    </tbody>
                  </Table>
                </TableWrap>
              </CardBody>
            </Card>
          )
        })
      )}
    </div>
  )
}
